Update action_runner.yml

diff --git a/.github/workflows/action_runner.yml b/.github/workflows/action_runner.yml
--- a/.github/workflows/action_runner.yml
+++ b/.github/workflows/action_runner.yml
@@ -1,74 +1,159 @@
-name: action_runner
 
+name: action_auto_utest
+
+# Controls when the action will run. Triggers the workflow on push or pull request
+# events but only for the master branch
 on:
+  # Runs at 16:00 UTC (BeiJing 00:00) on the 1st of every month
+  schedule:
+    - cron:  '0 16 1 * *'
+  push:
+    branches:
+      - master
+    paths-ignore:
+      - documentation/**
+      - '**/README.md'
+      - '**/README_zh.md'
   pull_request:
-    types: [opened, synchronize, reopened]
+    branches:
+      - master
+    paths-ignore:
+      - documentation/**
+      - '**/README.md'
+      - '**/README_zh.md'
+
+permissions:
+  contents: read # to fetch code (actions/checkout)
 
 jobs:
-  review-pr:
-    runs-on: ubuntu-latest
-    
+  test:
+    runs-on: ubuntu-22.04
+    name: ${{ matrix.legs.UTEST }}
+    if: github.repository_owner == 'Nedki-L'
+    strategy:
+      fail-fast: false
+      matrix:
+       legs:
+         - {UTEST: "qemu-vexpress-a9", RTT_BSP: "bsp/qemu-vexpress-a9",    QEMU_ARCH: "arm",      QEMU_MACHINE: "vexpress-a9", CONFIG_FILE: "config/default.cfg", SD_FILE: "sd.bin", RUN: "yes"}
+         - {UTEST: "qemu-virt64-aarch64", RTT_BSP: "bsp/qemu-virt64-aarch64", QEMU_ARCH: "aarch64",  QEMU_MACHINE: "virt",  CONFIG_FILE: "config/default.cfg",   SD_FILE: "sd.bin", RUN: "no"}
+         - {UTEST: "qemu-virt64-riscv", RTT_BSP: "bsp/qemu-virt64-riscv",   QEMU_ARCH: "riscv64",  QEMU_MACHINE: "virt",  CONFIG_FILE: "config/default.cfg",   SD_FILE: "None", RUN: "yes"}
+    env:
+      TEST_QEMU_ARCH: ${{ matrix.legs.QEMU_ARCH }}
+      TEST_QEMU_MACHINE: ${{ matrix.legs.QEMU_MACHINE }}
+      TEST_BSP_ROOT: ${{ matrix.legs.RTT_BSP }}
+      TEST_CONFIG_FILE: ${{ matrix.legs.CONFIG_FILE }}
+      TEST_SD_FILE: ${{ matrix.legs.SD_FILE }}
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+    - uses: actions/checkout@v4
 
-    - name: Set up Node.js (for JSON parsing)
-      uses: actions/setup-node@v2
-      with:
-        node-version: '14'
-
-    - name: Parse MAINTAINER.json and get affected owners
+    - name: Install Tools
+      shell: bash
       run: |
-        # Load MAINTAINER.json and parse it
-        maintainer_json=$(cat MAINTAINER.json)
-        
-        # Get list of modified files in the PR
-        pr_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
-        
-        # Parse the MAINTAINER.json to create a mapping of path to owners
-        declare -A tag_owners
+        sudo apt-get update
+        sudo apt-get -yqq install scons qemu-system git
+        pip3 install kconfiglib
 
-        for entry in $(echo "$maintainer_json" | jq -r '.[] | @base64'); do
-          _jq() {
-            echo ${entry} | base64 --decode | jq -r ${1}
-          }
+    - name: Install Arm ToolChains
+      if: ${{ matrix.legs.QEMU_ARCH == 'arm' && matrix.legs.UTEST != 'rtsmart/arm' && success() }}
+      shell: bash
+      run: |
+        wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.3/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
+        sudo tar xjf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -C /opt
+        /opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc --version
+        echo "RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-10-2020-q4-major/bin" >> $GITHUB_ENV
 
-          tag=$(echo "$entry" | _jq '.tag')
-          path=$(echo "$entry" | _jq '.path')
-          owners=$(echo "$entry" | _jq '.owners')
+    - name: Install Arm Musl ToolChains
+      if: ${{ matrix.legs.QEMU_ARCH == 'arm' && matrix.legs.UTEST == 'rtsmart/arm' && success() }}
+      shell: bash
+      run: |
+        wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.7/arm-linux-musleabi_for_x86_64-pc-linux-gnu_stable.tar.bz2
+        sudo tar xjf arm-linux-musleabi_for_x86_64-pc-linux-gnu_stable.tar.bz2 -C /opt
+        /opt/arm-linux-musleabi_for_x86_64-pc-linux-gnu/bin/arm-linux-musleabi-gcc --version
+        echo "RTT_EXEC_PATH=/opt/arm-linux-musleabi_for_x86_64-pc-linux-gnu/bin" >> $GITHUB_ENV
+        echo "RTT_CC_PREFIX=arm-linux-musleabi-" >> $GITHUB_ENV
 
-          # Convert owners into GitHub IDs
-          owner_github_ids=$(echo "$owners" | sed -E 's/.*\(([^)]+)\)<.*>/@\1/g')
+    - name: Install RISC-V ToolChains
+      if: ${{ matrix.legs.QEMU_ARCH == 'riscv64' && matrix.legs.UTEST != 'rtsmart/riscv64' && success() }}
+      run: |
+        wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.4/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz
+        sudo tar zxvf riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz -C /opt
+        /opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/riscv64-unknown-elf-gcc --version
+        echo "RTT_EXEC_PATH=/opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin" >> $GITHUB_ENV
 
-          tag_owners["$path"]="$tag_owners[$path] $owner_github_ids"
-        done
+    - name: Install RISC-V Musl ToolChains
+      if: ${{ matrix.legs.QEMU_ARCH == 'riscv64' && matrix.legs.UTEST == 'rtsmart/riscv64' && success() }}
+      shell: bash
+      run: |
+        wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.7/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu_latest.tar.bz2
+        sudo tar xjf riscv64-linux-musleabi_for_x86_64-pc-linux-gnu_latest.tar.bz2 -C /opt
+        /opt/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu/bin/riscv64-unknown-linux-musl-gcc --version
+        echo "RTT_EXEC_PATH=/opt/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu/bin" >> $GITHUB_ENV
+        echo "RTT_CC_PREFIX=riscv64-unknown-linux-musl-" >> $GITHUB_ENV
 
-        # Check which tag needs to be triggered based on modified files
-        affected_tags=()
-        for file in $pr_files; do
-          for path in "${!tag_owners[@]}"; do
-            if [[ $file == $path* ]]; then
-              affected_tags+=("${tag_owners[$path]}")
-            fi
-          done
-        done
+    - name: Install AARCH64 Musl ToolChains
+      if: ${{ matrix.legs.QEMU_ARCH == 'aarch64' && matrix.legs.UTEST == 'rtsmart/aarch64' && success() }}
+      shell: bash
+      run: |
+        wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.7/aarch64-linux-musleabi_for_x86_64-pc-linux-gnu_stable.tar.bz2
+        sudo tar xjf aarch64-linux-musleabi_for_x86_64-pc-linux-gnu_stable.tar.bz2 -C /opt
+        /opt/aarch64-linux-musleabi_for_x86_64-pc-linux-gnu/bin/aarch64-linux-musleabi-gcc --version
+        echo "RTT_EXEC_PATH=/opt/aarch64-linux-musleabi_for_x86_64-pc-linux-gnu/bin" >> $GITHUB_ENV
+        echo "RTT_CC_PREFIX=aarch64-linux-musleabi-" >> $GITHUB_ENV
 
-        # If affected tags found, prepare the comment
-        if [ ${#affected_tags[@]} -gt 0 ]; then
-          tags_unique=$(echo "${affected_tags[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')
-          
-          # Format and send the comment
-          pr_number=${{ github.event.pull_request.number }}
-          comment_body="timestamp: $(date)
-          
-Reviewer: ${tags_unique}
+    - name: CPP11 Preprocessing Toolchain
+      if: ${{ matrix.legs.QEMU_ARCH == 'arm' && matrix.legs.UTEST == 'components/cpp11' && success() }}
+      shell: bash
+      run: |
+        # Delete the following files
+        sudo rm -f /opt/gcc-arm-none-eabi-10-2020-q4-major/arm-none-eabi/include/c++/10.2.1/thread
+        sudo rm -f /opt/gcc-arm-none-eabi-10-2020-q4-major/arm-none-eabi/include/c++/10.2.1/mutex
+        sudo rm -f /opt/gcc-arm-none-eabi-10-2020-q4-major/arm-none-eabi/include/c++/10.2.1/condition_variable
+        sudo rm -f /opt/gcc-arm-none-eabi-10-2020-q4-major/arm-none-eabi/include/c++/10.2.1/future
+        sudo rm -f /opt/gcc-arm-none-eabi-10-2020-q4-major/arm-none-eabi/include/pthread.h
+        # Clear the contents of the following files
+        sudo cat /dev/null > /opt/gcc-arm-none-eabi-10-2020-q4-major/arm-none-eabi/include/sys/_pthreadtypes.h
+        # Clear -fno-exceptions in rtconfig.py
+        sed -i 's/-fno-exceptions/ /g' $TEST_BSP_ROOT/rtconfig.py
 
-Modified files:
-$(echo "$pr_files")"
+    - name: Build BSP
+      run: |
+        echo CONFIG_RT_USING_UTESTCASES=y >> $TEST_BSP_ROOT/.config
+        cat .github/utest/$TEST_CONFIG_FILE >> $TEST_BSP_ROOT/.config
+        scons --pyconfig-silent -C $TEST_BSP_ROOT
+        scons -j$(nproc) --strict -C $TEST_BSP_ROOT
 
-          curl -X POST \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            -H "Content-Type: application/json" \
-            -d '{"body":"'"$comment_body"'"}' \
-            "https://api.github.com/repos/${{ github.repository }}/issues/$pr_number/comments"
+    - name: Start run Test
+      if: ${{matrix.legs.RUN == 'yes' && success() }}
+      run: |
+        if [ $TEST_SD_FILE != "None" ]; then
+          dd if=/dev/zero of=$TEST_BSP_ROOT/sd.bin bs=1024 count=65536
+          qemu-system-$TEST_QEMU_ARCH -nographic -M $TEST_QEMU_MACHINE -kernel $TEST_BSP_ROOT/rtthread.bin -nographic -sd $TEST_BSP_ROOT/sd.bin > qemu_output_${TEST_QEMU_ARCH}.log 2>&1 &
+        else
+          qemu-system-$TEST_QEMU_ARCH -nographic -M $TEST_QEMU_MACHINE -kernel $TEST_BSP_ROOT/rtthread.bin -nographic > qemu_output_${TEST_QEMU_ARCH}.log 2>&1 &
         fi
+
+        cat qemu_output_${TEST_QEMU_ARCH}.log
+
+    # - name: Monitor qemu log
+    #   if: ${{matrix.legs.RUN == 'yes' && success() }}
+    #   run: |
+    #     FAILURE_DETECTED=false
+    #     ERROR_LOGS=""
+        
+    #     tail -n 0 -f qemu_output_${TEST_QEMU_ARCH}.log | while read line; do
+    #       echo $line
+    #       if [[ "$line" == *"[  FAILED  ] [ result   ]"* ]]; then
+    #         ERROR_LOGS="$ERROR_LOGS$line"$'\n'
+    #         FAILURE_DETECTED=true
+    #       fi
+          
+    #       if [[ "$line" == *"[==========] [ utest    ] end"* ]]; then
+    #         echo "Utest run completed. Exiting log monitoring..."
+    #         if $FAILURE_DETECTED; then
+    #           echo "Error: Failures detected in logs. Below are the failure details..."
+    #           echo "$ERROR_LOGS"
+    #           exit 1
+    #         fi
+    #         break
+    #       fi
+    #     done
